---
- name: configure host
  hosts: all
  become: true
  roles:
    - common
  
- name: configure backend server
  hosts: _a03_backend_server
  gather_facts: false
  roles:
    - backend

- name: configure web server
  hosts: _a03_web_server
  gather_facts: false
  roles:
    - web